import express from "express";
const router = express.Router();
import { createEvent } from "../controllers/createevent.controller.js";
import { getEvent } from "../controllers/getevent.controller.js";
import { getEventById } from "../controllers/geteventbyid.controller.js";
import { register } from "../controllers/register.controller.js";
router.post("/createevent", createEvent);
router.get("/getevent", getEvent);
router.get("/geteventbyid", getEventById);
router.post("/register", register);
export default router;
