import mongoose from "mongoose";
const eventSchema = mongoose.Schema({
  image_url: String,
  title: String,
  description: String,
  start_date: String,
  end_date: String,
  time: String,
  duration: String,
  google_form_link: String,
  coordinator_name: String,
  details: String,
  category: String,
  registers: [String],
  guest_name: String,
  guest_organisation: String,
  guest_field: String,
  guest_exp: String,
  guest_email: String,
  hallid: String,
  rating: [Number],
  feedback: [{}],
  committe_id: String,
  ended: Boolean,
});
export default mongoose.model("events", eventSchema);
